### ISSUE TITLE
haproxy config trouble

### ISSUE THREAD

**Issue by Fantomatic** [pawankkamboj/HA-kubernetes-ansible#11]
Hi, 
I would like to know which haproxy version you used when you tested it ? 
It seem that with the 1.7 at least there is a problem with the 'option httplog' which is not usable with front end 'api-https' ( it say it need 'mode http'). Even so it doesn't seem to crash anything since it switch to 'option tcplog'.

**Comment by pawankkamboj** [comment]
I used latest haproxy image, yes we can remove that option for https

**Comment by pawankkamboj** [comment]
Fixed and commited
