### ISSUE TITLE
Addon playbook doesn't wait enough for running containers

### ISSUE THREAD

**Issue by mhmxs** [pawankkamboj/HA-kubernetes-ansible#14]
During execution it throws an error that addon container is not running. Those errors don't break the process, so it works as well, but would be nice to wait more, or eliminate check totally

**Comment by pawankkamboj** [comment]
There is check in every addon deployment, which check if addon is already running, if not then playbook create, we can ignore them,

We can also remove these check because kubernetes throw error if object is already deployed.

**Comment by mhmxs** [comment]
Ohh, i see. I thought it deploys the addon and than check it, sorry just saw the error there and didn't investigate :)
