### ISSUE TITLE
Api load balancer

### ISSUE THREAD

**Issue by dsever** [pawankkamboj/HA-kubernetes-ansible#18]
Hi,, 

Can you please explain me this part of configuration:
#- api secure port and api loadbalancer IP
api_secure_port: 5443
api_lb_ip: https://192.168.50.11 # it should be haproxy host IP or network load balancer IP  # if using onle one api server then setup IP of it
lb_ip: 192.168.50.11

#- setup haproxy for loadbalancing
haproxy: true  # set false when already physical loadbalancer available
haproxy_dir: /etc/haproxy
haproxy_monitor_port: 9090
admin_user: admin

Because I don't understand in your sample this IP 192.168.50.11 is not related to the kubernetes cluster?

Thanks

**Comment by pawankkamboj** [comment]
api_secure_port - > https port exposed by kube-api-server 
api_lb_ip -> address use by all cluster components to connect to kube api server, if you have multiple api severs and lb in front of them then you lb ip, if not then it should be api server ip it self
lb_ip - > same as above but only diff is it is a IP above is complete complete URL to access api servers

haproxy setting - > if you are using multiple api servers and you dont have physical LB then haproxy fit in that case, all these are setting related to haproxy, haproxy will run on any one master machine as a pod, the above api_lb_ip refer to this haproxy machine address.

Hope it helps

**Comment by dsever** [comment]
Thanks, sounds reasonable
I will try to test architecture, and then let you know is it clear now :)

Dubravko

**Comment by rnunes-bullhorn** [comment]
Shouldn't openssl.conf.j2 contain IP.2 = {{ lb_ip }} for kubectl connectivity? Getting invalid cert without it..
