### ISSUE TITLE
Flannel configuration

### ISSUE THREAD

**Issue by dsever** [pawankkamboj/HA-kubernetes-ansible#21]
Hi 

maybe you have two little mistakes:
file HA-kubernetes-ansible/roles/flannel/tasks/main.yml

line 15 for https sould be 
peers: "{% for hostname in groups['etcd'] %}{{etcd_peer_url_scheme}}://{{ hostname }}:2379{% if not loop.last %},{% endif %}{% endfor %}"
And you have hadcoded http

A another you have missed  { in line 39.

Dubravko

**Comment by pawankkamboj** [comment]
Thanks, fixed now.
