### ISSUE TITLE
centos atomic

### ISSUE THREAD

**Issue by dimthe** [pawankkamboj/HA-kubernetes-ansible#23]
hi 
is this role just for centos or can it also work on centos atomic hosts ?

**Comment by pawankkamboj** [comment]
Autoscale work on all kubernetes distribution. It is a feature which work
on Replication controller , deployment, you can  setup autoscale for both

**Comment by dimthe** [comment]
Hello 
i mean your ansible role , can it be executed as is on atomic hosts ( centos atomic ) ? i am asking becase yum is missing from atomic images

**Comment by pawankkamboj** [comment]
No, it is only for centos7
