### ISSUE TITLE
kube-dns in CrashLoopBackOff

### ISSUE THREAD

**Issue by ralberto** [pawankkamboj/HA-kubernetes-ansible#25]
Hi.
I'm trying to setup kubernetes cluster using the provided ansible playbooks. However, the addon kube-dns does not work. The following error in shown in the logs:

`I0530 10:15:33.126625       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://192.168.14.119/api/v1/namespaces/default/services/kubernetes: x509: failed to load system roots and no roots provided. Sleeping 1s before retrying.

E0530 10:15:33.140844       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://192.168.14.119/api/v1/services?resourceVersion=0: x509: failed to load system roots and no roots provided
`

Is this a problem with the scripts? Something that I'm missing?

Thanks in advance.

**Comment by pawankkamboj** [comment]
Nothing problem in setup, make sure that your cluster is fully up and working fine
