### ISSUE TITLE
RBAC working out of the box?

### ISSUE THREAD

**Issue by sonoroot** [pawankkamboj/HA-kubernetes-ansible#28]
Hi,
thanks for this playbook, great job.
I don't want to use ABAC, so I don't populate the related group_var/all.yaml variables; the cluster gets deployed but the api-server container is in constant restart.
My question is, for the way this deployment is designed, will it work with RBAC or must be ABAC?
If it is supposed to work with RBAC as well, then I will invest more time in investigating the problem I've got. 
Thanks,
Sono

**Comment by pawankkamboj** [comment]
It will work with ABAC, will modify it for ABAC. Tomorrow will be available.

**Comment by sonoroot** [comment]
That would be great, you mean you will modify it for RBAC I guess.

**Comment by pawankkamboj** [comment]
you can try now now added for RBAC as well

**Comment by sonoroot** [comment]
OK, I will pull the repo and try ASAP and let you know!
Thank you

**Comment by sonoroot** [comment]
Thanks a lot!
