### ISSUE TITLE
sslhost

### ISSUE THREAD

**Issue by Fantomatic** [pawankkamboj/HA-kubernetes-ansible#4]
Your sslhost need to be the ansible host in the state of your files. You used the command copy to copy files to other remotes. Which is limited to localhost as source. Maybe you should already filled the inventory with it. Or i missed something and in that case i apologize. 

( sorry for theses "issue" but there isn't really a chat for this kind of stuff and i haven't the time to pull request theses days )

**Comment by pawankkamboj** [comment]
yes, it is already there in inventory file and it should be ansible host.

**Comment by jenciso** [comment]
I would like have one inventory example for this issue. Could you write a little example using multi-master and multi-node and sslhost... Thanks

**Comment by pawankkamboj** [comment]
here is sample

[etcd]
192.168.61.71
192.168.61.72
192.168.61.73
[masters]
192.168.61.71
192.168.61.72
192.168.61.73
[sslhost] #- it should be your ansible host IP.
192.168.61.6
[node]
192.168.61.74
192.168.61.75
192.168.61.76
