### ISSUE TITLE
error flannel configuration into etcd

### ISSUE THREAD

**Issue by harryliu123** [pawankkamboj/HA-kubernetes-ansible#9]
TASK [flannel : Insert flannel configuration into etcd] ************************
fatal: [10.1.52.143]: FAILED! => {"failed": true, "msg": "the field 'args' has a                                                      n invalid value, which appears to include a variable that is undefined. The erro                                                      r was: 'etcd' is undefined\n\nThe error appears to have been in '/root/HA-kubern                                                      etes-ansible/roles/flannel/tasks/main.yml': line 22, column 3, but may\nbe elsew                                                      here in the file depending on the exact syntax problem.\n\nThe offending line ap                                                      pears to be:\n\n\n- name: Insert flannel configuration into etcd\n  ^ here\n"}
fatal: [10.1.52.144]: FAILED! => {"failed": true, "msg": "the field 'args' has a                                                      n invalid value, which appears to include a variable that is undefined. The erro                                                      r was: 'etcd' is undefined\n\nThe error appears to have been in '/root/HA-kubern                                                      etes-ansible/roles/flannel/tasks/main.yml': line 22, column 3, but may\nbe elsew                                                      here in the file depending on the exact syntax problem.\n\nThe offending line ap                                                      pears to be:\n\n\n- name: Insert flannel configuration into etcd\n  ^ here\n"}
fatal: [10.1.52.142]: FAILED! => {"failed": true, "msg": "the field 'args' has a                                                      n invalid value, which appears to include a variable that is undefined. The erro                                                      r was: 'etcd' is undefined\n\nThe error appears to have been in '/root/HA-kubern                                                      etes-ansible/roles/flannel/tasks/main.yml': line 22, column 3, but may\nbe elsew                                                      here in the file depending on the exact syntax problem.\n\nThe offending line ap                                                      pears to be:\n\n\n- name: Insert flannel configuration into etcd\n  ^ here\n"}
fatal: [10.1.52.135]: FAILED! => {"failed": true, "msg": "the field 'args' has a                                                      n invalid value, which appears to include a variable that is undefined. The erro                                                      r was: 'etcd' is undefined\n\nThe error appears to have been in '/root/HA-kubern                                                      etes-ansible/roles/flannel/tasks/main.yml': line 22, column 3, but may\nbe elsew                                                      here in the file depending on the exact syntax problem.\n\nThe offending line ap                                                      pears to be:\n\n\n- name: Insert flannel configuration into etcd\n  ^ here\n"}
        to retry, use: --limit @/root/HA-kubernetes-ansible/cluster.retry

PLAY RECAP *********************************************************************
10.1.52.135                : ok=38   changed=25   unreachable=0    failed=1
10.1.52.142                : ok=33   changed=21   unreachable=0    failed=1
10.1.52.143                : ok=25   changed=17   unreachable=0    failed=1
10.1.52.144                : ok=25   changed=17   unreachable=0    failed=1

**Comment by harryliu123** [comment]
role/haproxy
[root@master1 HA-kubernetes-ansible]# cat roles/haproxy/tasks/main.yml
---
- name: create kubernetes manifests config directory
  when: haproxy
  file: path={{ manifest_config_dir }} state=directory

- name: create haproxy config directory
  file: path={{ haproxy_dir }} state=directory
  register: ha_dir
  delegate_to: "{{ groups['masters'][0] }}"

- name: copy haproxy json config file
  template: src="haproxy.json.j2" dest={{ manifest_config_dir }}/haproxy.json
  register: ha_json
  delegate_to: "{{ groups['masters'][0] }}"

- name: copy haproxy config file
  template: src="haproxy.cfg.j2" dest={{ haproxy_dir }}/haproxy.cfg
  register: ha_config
  delegate_to: "{{ groups['masters'][0] }}"

this role only create file, not run it ?

**Comment by pawankkamboj** [comment]
yes, will not run, it run as a pod on master[0] server, haproxy.json put in manifest dir of kubelet and when you start master it start haproxy also.

**Comment by harryliu123** [comment]
yes! thank you  support
 my haproxy run on docker on my master[0] but i did not find  nlb ip(haproxy host IP) in my network 


[root@master1 HA-kubernetes-ansible]# docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
docker.io/haproxy                                        latest              c0a3eb080707        13 days ago         138 MB

[root@master1 HA-kubernetes-ansible]# docker inspect c0a3eb080707
[
    {
        "Id": "sha256:c0a3eb080707b1d20606f888754f3866f45783253870db0856f4d0ad7e5cd8d0",
        "RepoTags": [
            "docker.io/haproxy:latest"
        ],
        "RepoDigests": [
            "docker.io/haproxy@sha256:6d7a503e62deeb887d0b3e8e4daa29a62e2accc2466a7e3b3ca3b7d7541ed89e"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2016-12-14T02:38:02.352002641Z",
        "Container": "9709ca79b523c855a943d8b6e57e280cee79e3e6c073214831a12b2d5d9e0e09",
        "ContainerConfig": {
            "Hostname": "45f28166fed1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HAPROXY_MAJOR=1.7",
                "HAPROXY_VERSION=1.7.1",
                "HAPROXY_MD5=d0acaae02e444039e11892ea31dde478"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"haproxy\" \"-f\" \"/usr/local/etc/haproxy/haproxy.cfg\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:ac3309edbb8368ea5716edf0fd649131ea7841f9d642f1f7770cee0283643e53",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.12.3",
        "Author": "",
        "Config": {
            "Hostname": "45f28166fed1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HAPROXY_MAJOR=1.7",
                "HAPROXY_VERSION=1.7.1",
                "HAPROXY_MD5=d0acaae02e444039e11892ea31dde478"
            ],
            "Cmd": [
                "haproxy",
                "-f",
                "/usr/local/etc/haproxy/haproxy.cfg"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:ac3309edbb8368ea5716edf0fd649131ea7841f9d642f1f7770cee0283643e53",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 137996507,
        "VirtualSize": 137996507,
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "27",
                "DeviceName": "docker-253:1-101004893-3519f868c0a6394257452c5e27f0bd5e4a197def65ad05f0cbcbdb91bfe763e1",
                "DeviceSize": "10737418240"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:b6ca02dfe5e62c58dacb1dec16eb42ed35761c15562485f9da9364bb7c90b9b3",
                "sha256:c6073d2b1fede34009cdb82057997e0a362d311fd508f459c518a748c8dbcc80",
                "sha256:fa8250cc14a4b6b4760510f0710521715e9020e498aae569f9a32768042353c5",
                "sha256:ec5f6eb6f16ea49fccdfce9823688a32aad1cfbd5dbd1c8336aab1d2494142d4"
            ]
        }
    }
]


i run  kubectl get pods
[root@master1 HA-kubernetes-ansible]#  kubectl get pods
No resources found.



# my all.yml
#- api secure port and api loadbalancer IP
api_secure_port: 5443
api_lb_ip: https://10.1.52.199 # it should be haproxy host IP or network load balancer IP  # if using onle one api server then setup IP of it
lb_ip: 10.1.52.199

# my inventory
[etcd]
10.1.52.135
10.1.52.142
[masters]
10.1.52.135
10.1.52.142
[sslhost]
10.1.52.135 # should be ansible host
[node]
10.1.52.143
10.1.52.144

**Comment by pawankkamboj** [comment]
haproxy pod run on host network of base machine, so IP for this pod is same as base IP, I use hostnetwork in pod.

also run below command to get output in verbose, share it
kubectl get pods -v 10
